[book]
title = "Self-taught software engineer"
authors = ["lonexw"]
language = "zh-CN"
multilingual = true
src = "src"

# book.toml
[output.html]
site-url = "/sse-book/"
git-repository-url = "https://github.com/lonexw/sse-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/lonexw/sse-book/edit/main/{path}"

